### ISSUE TITLE
Doesn't support python3

### ISSUE THREAD

**Issue by matthewleemle** [ininex/geofire-python#4]
Traceback (most recent call last):
  File "/Users/matthew/Desktop/Telus/ddb.py", line 1, in <module>
    from GeoFire.geofire import GeoFire
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GeoFire/geofire.py", line 2, in <module>
    from pyrebase import pyrebase
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyrebase/pyrebase.py", line 1, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):

**Comment by drydenwiebe** [comment]
I have found this also
